name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout simpleICP
        uses: actions/checkout@v2
        with:
          path: 'simpleICP'
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10.4
        with:
          vcpkgGitCommitId: 34f072dfcb8b9356e6ed2c74947f87390ddb2706
          vcpkgJsonGlob: '**/.github/workflows/vcpkg.json'
          # runVcpkgInstall: true
      - name: Build
        run: ./build.sh
        working-directory: simpleICP/c++
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: simpleICP
          path: simpleICP/c++/build/simpleicp
